version: '3.4'

services:
  cortex.in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  cortex.out.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
networks:
  default:
    external:
      name: sample_default